apiVersion: v1
kind: ConfigMap
metadata:
  name: ticket-system-config
  namespace: ticket-system
data:
  DB_URL: "jdbc:postgresql://postgres:5432/ticket_system"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  SERVER_PORT: "8080"
  SPRING_PROFILES_ACTIVE: "prod,sentry,resilience"
  STORAGE_TYPE: "local"
  JWT_EXPIRATION: "900000"
  MAIL_HOST: "smtp.gmail.com"
  MAIL_PORT: "587"
